### ISSUE TITLE
Visualizing the bag file

### ISSUE THREAD

**Issue by hachbani2019** [CPFL/ouster#11]
Hi,
I'm started learning ROS for over like a month now. I just got a Ouster OS-1 16, first thing I should do is learn how to visualize the bag file,I've followed the ReadMe instructions, but can't figure out why it doesn't work. 

**First:**
I've tried to run `roslaunch ouster_driver os1.launch replay:=true`, then play the bag file via `rosbag play --clock <bagfile>` and finally visualize using Rviz via this command: `rviz -d /path/to/ouster_driver/rviz/viz.rviz` But nothing seems to be happening on the Rviz screen. The Global status on Rviz is set to "Warn" with as an error: 
> No tf data.  Actual error: Fixed Frame [os1] does not exist

**Second:** 
In the ReadMe it says : 
> Note: os1_node/lidar_packets and os1_node/imu_packets are the "raw data" topics, while os1_node/points is the ROS compatible XYZ topic and os1_node/imu is the ROS compatible IMU topic, 

So, I go looking for this os1_node/points topic but can't find it in the rostopic list, I try even though to echo it, but nothing happens. 

PS: I'm using random bag files I downloaded from the bag files link provided in the ReadMe.

Anyone can help me to visualize the content of this bag file please ? 

Thanks in advance  !!

PS2: Please, keep in mind that I've only been learning ROS for like a month ago, so, if you can keep it as simple as you can in the comments It'd be really helpful

**Comment by hachbani2019** [comment]
Solved this by using the official ouster project. Hit me up if you're encountering any similar issue, I may not help you but at least we may learn from each other !

**Comment by aaravrav142** [comment]
Hi @hachbani2019, I am facing similar problem, can you provide help to solve the issue. No data been published on the rviz screen. I have the bag file downloaded from the page. I also have the official ouster_example repository cloned and catkin_make. 
Thanks

**Comment by laghbani** [comment]
I am facing te same problem

**Comment by kaku-KRS** [comment]
too

**Comment by amc-nu** [comment]
Please refer to the official driver. This project is no longer maintained.
https://github.com/ouster-lidar/ouster_example
