### ISSUE TITLE
compatible with firmware 1.13???

### ISSUE THREAD

**Issue by swjtuyang** [CPFL/ouster#17]
pulse_mode no longer in 1.13?

Please update ..

**Comment by swjtuyang** [comment]
with os-1-16

**Comment by swjtuyang** [comment]
if I ignore this;
if (product_str != std::string("OS-1-64")) {
    	std::cout << "Error: this driver currently only supports Ouster model \"OS-1-64\"." << std::endl;
    	return std::shared_ptr<client>();
    }

will it work?

**Comment by martinmagnusson** [comment]
I guess that commenting/ignoring the above will not help, since the issue is that 
``` 
On firmware version "v1.13.0" the "pulse_mode" parameter is no longer available, will ignore it.
error: Invalid configuration key
init_client: command "set_config_param window_rejection_enable 1" failed with "error: Invalid configuration key"
```
At least for me, after upgrading my OS-1-64 to firmware 1.13

**Comment by martinmagnusson** [comment]
So we'll have to use the official driver instead: https://github.com/ouster-lidar/ouster_example

Just be aware that the build instructions there are somewhat broken. You should not do `export CMAKE_PREFIX_PATH=/path/to/ouster_example`
