### ISSUE TITLE
The problem of ROS driver

### ISSUE THREAD

**Issue by yulan0215** [CPFL/ouster#19]
Hi:

Recently I used your Ouster driver in order to change the format into Velodyne format.

I set the launch file like:
![image](https://user-images.githubusercontent.com/62309959/187070074-ae32d725-b26d-493a-aa23-7acffda19915.png)
 
But when I launch the os1.launch file I met this problem:

![image](https://user-images.githubusercontent.com/62309959/187070108-a3baeddc-2d6f-483a-aeb4-ade40616fc31.png)

I will appreciate if you can give me some ideas. Thx

**Comment by amc-nu** [comment]
This project is no longer under maintenance. Please try the official driver instead.
https://github.com/ouster-lidar/ouster_example

**Comment by yulan0215** [comment]
> 

Thx, I am sorry do you have  any idea about convert the format into Velodyne format? Thx
