### ISSUE TITLE
[error] pulse parameter makes ouster initialization

### ISSUE THREAD

**Issue by ghost** [CPFL/ouster#4]
I use ouster lidar in autoware and it shows error message. I do some experiments for fix this and I found their is no "pulse_mode" setting in "set_config_param". Please check this part. Finally I commented "success &= do_cmd("set_config_param", "pulse_mode " + _pulse_mode_str);" line in src/os1.cpp, and then it worked well.

![ouster_error](https://user-images.githubusercontent.com/12016607/51955061-d12abc80-2485-11e9-8a90-87e4fdce3188.png)
I printed all options and values. As you can see pulse mode makes error.

I am using ouster_os1 64 channel.

**Comment by alexandrx** [comment]
Sorry for the long delay. 

Perhaps is a firmware support problem. Could you tell me the firmware version of your OS-1-64?
Just run  `nc <YOUR-OS-1-64-IP-ADDRESS> 7501` on a terminal, then type:
```
get_sensor_info
```
and check for the `build_rev` field. Our OS-1-64 is running on version "1.9.0"

**Comment by ghost** [comment]
--------
get_sensor_info
{"prod_line": "OS-1-64", "prod_pn": "840-101396-03", "prod_sn": "991840000699", "base_pn": "000-101323-03", "base_sn": "101837000527", "image_rev": "ousteros-image-prod-aries-v1.10.0-20181211235856", "build_rev": "v1.10.0", "proto_rev": "v1.1.1", "build_date": "2018-12-11T23:23:23Z", "status": "UNCONFIGURED"}
---------
This is the result.
My build version is 1.10.0. I got it. So are you gonna support this version too?

**Comment by alexandrx** [comment]
@4artit 
The new version (PR #9, just merged into `autoware_branch`) checks the current value of parameters on the sensor and reinitializes only if there are changes. This because Ouster marks parameter changes as staged so it requires reinitialization to make the active, and reinitialization is slow.
~But you still need the newest firmware.~(didn't notice you already updated)
I have to check that version.

**Comment by alexandrx** [comment]
@4artit 
I just released a new version of the driver which works also on firmware version 1.10.
Please check.
