### ISSUE TITLE
[error] Cannot start ./viz

### ISSUE THREAD

**Issue by Scarabrine** [CPFL/ouster#5]
Hi, Ouster,

I just install your lidar on our vehicle's ECU, we run on Ubuntu. After I allocate the IP address correctly and start the visualizer by the command `./viz <os1_hostname> <udp_data_dest_ip>`, there is following error:

./viz os1-991832000882  192.168.1.1
Sensor: os1-991832000882 UDP Destination:192.168.1.1
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  39
  Current serial number in output stream:  40

I have checked the os1-hostname and ip address are both correct, so what the problem maybe?

More information:
![image](https://user-images.githubusercontent.com/29248149/52014270-1f06eb00-24ad-11e9-94ff-8630c4d18bf4.png)

**Comment by ghost** [comment]
did you try official ouster ros driver node also? This repo is little bit changed form from official one for using ouster in autoware.
[ouster_link](https://github.com/ouster-lidar/ouster_example)
If this repo also do not work, please tell me

**Comment by amc-nu** [comment]
@Scarabrine this is a specific ROS package, we removed the non-ROS related stuff.

if you are in a ROS environment:
1. Source your terminal: `$ source devel/setup.bash`
1. `$ roslaunch ouster_ros os1.launch`
1. `$ rviz `
1. Press the Add button from the Displays. 
1. Select By topic tab
1. Select PointCloud topic `/points_raw`.

You can see the configurable parameters here:
https://github.com/CPFL/ouster/blob/autoware_branch/launch/os1.launch

**Comment by amc-nu** [comment]
Moreover, if you are using Autoware you can just use the UI to launch the node.

![image](https://user-images.githubusercontent.com/7009053/52026579-b3278f80-254b-11e9-922d-cc49f68185ca.png)

**Comment by Scarabrine** [comment]
Thank you @4artit and @amc-nu , I think I have found the problem. This is an error related to the x server / my graphics drivers. I will try your suggestions. I will keep you guys update If I solve this problem.
